# BFSI Bank Customer Churn Analysis

An end-to-end Excel analytics project on a 10,000-customer retail bank portfolio: data quality checks, transformation, EDA, statistical summary, cross-tab analysis, an interactive dashboard, business Q&A, VBA macro source, and a full what-if / scenario analysis ending in a management recommendation.

## Headline findings

| Metric | Result |
|---|---|
| Overall churn rate | **20.37%** (2,037 of 10,000) |
| Balance held by churned customers | **$185.6M (24.26%** of portfolio balance) |
| Highest-risk geography | Germany, **32.44%** (France 16.15%, Spain 16.67%) |
| Highest-risk age band | 51-60, **56.21%** |
| Engagement gap | Inactive 26.85% vs Active 14.27% |
| Product count | 2 products safest (7.58%); 3-4 products 83-100% |
| Not drivers | CreditScore, Salary, Tenure (near-zero correlation) |

**Key insight:** churn *rate* and balance *protected* are different goals. Broad levers reach a 15% churn target easily, but protecting 80% of at-risk balance also requires a dedicated high-value retention track.

## Workbook map

| Sheet | Purpose |
|---|---|
| `Transformed_Data` | 21 live-formula columns (age group, balance category, risk bands, etc.) |
| `EDA_Analysis` | Distributions, churn by segment, outliers (IQR), correlations |
| `Statistical_Summary_Work` | Descriptive stats overall and by segment |
| `Pivot_Analysis` | 10 pivot-style cross-tabs with charts |
| `Dashboard_Live` | 6 dropdown filters driving 7 KPI cards and 4 charts |
| `Business_Answers` | 15 business questions: calculation, insight, recommendation |
| `Macro_Documentation` | 12 VBA macros (paste-ready source) |
| `WhatIf_*` (5 sheets) | Scenarios, Goal Seek, sensitivity tables, narrative questions, integrated project |
| `Final_Recommendation` | Management report |
| `Interview_Talking_Points` | Pitch, key numbers, Q&A |

## Method notes and limitations

- All outputs are live formulas against `Transformed_Data`; every figure was cross-checked against an independent pandas calculation.
- **Pivot tables, slicers, Scenario Manager, Goal Seek and Data Tables** are formula-driven equivalents (these Excel features cannot be generated by script). Each sheet documents how to rebuild the native feature.
- **VBA** is provided as source, not compiled. Paste via `Alt+F11` and save as `.xlsm`.
- Scenario levers that overlap are decomposed into mutually exclusive segments; Germany and High-Value overlays are layered additively (an approximation).
- Break-even inputs (CAC $500, 2% margin, $500K budget) are assumptions.

## How to use

1. Open `BFSI_Bank_Customer_Churn_Analysis_Project.xlsx` in Excel.
2. Start at `Final_Recommendation`, then explore `Dashboard_Live` (change the yellow filters).
3. Edit yellow assumption cells in the `WhatIf_*` sheets to test your own scenarios.

## Source data

Public bank customer churn dataset (10,000 rows, 14 fields: CreditScore, Geography, Gender, Age, Tenure, Balance, NumOfProducts, HasCrCard, IsActiveMember, EstimatedSalary, Exited).
